site_name: AudioMuse-AI Documentation
docs_dir: web
site_url: https://neptunehub.github.io/AudioMuse-AI/
repo_url: https://github.com/NeptuneHub/AudioMuse-AI
repo_name: GitHub
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Algorithm: ALGORITHM.md
  - Architecture: ARCHITECTURE.md
  - Multiple Music Servers: MULTI_SERVER.md
  - Deployment: DEPLOYMENT.md
  - Navidrome Setup: NAVIDROME.md
  - GPU: GPU.md
  - Parameters: PARAMETERS.md
  - Authentication: AUTH.md
  - Plugins: PLUGIN.md
  - Error Codes: ERROR_CODES.md
  - FAQ: FAQ.md

theme: readthedocs
