[supervisord]
nodaemon=true
logfile=/dev/null           ; Run supervisord in the foreground
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0777

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:flask]
command=/usr/local/bin/gunicorn --bind 0.0.0.0:8000 --workers 1 --threads 4 --worker-class gthread --keep-alive 5 --timeout 300 --capture-output --error-logfile - --access-logfile - app:app
autostart=false
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:rq-worker-high]
command=/usr/bin/python3 -u /app/rq_worker_high_priority.py
autostart=false
autorestart=true
stopsignal=TERM             ; Send SIGTERM to the process on stop
stopasgroup=true
killasgroup=true
stopwaitsecs=5
environment=PYTHONUNBUFFERED=1
stdout_logfile=/dev/stdout  ; Redirect stdout to container's stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr  ; Redirect stderr to container's stderr
stderr_logfile_maxbytes=0

[program:rq-worker-default]
command=/usr/bin/python3 -u /app/rq_worker.py
autostart=false
autorestart=true
stopsignal=TERM             ; Send SIGTERM to the process on stop
stopasgroup=true
killasgroup=true
stopwaitsecs=5
environment=PYTHONUNBUFFERED=1
stdout_logfile=/dev/stdout  ; Redirect stdout to container's stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr  ; Redirect stderr to container's stderr
stderr_logfile_maxbytes=0

[program:rq-janitor]
command=/usr/bin/python3 -u /app/rq_janitor.py
autostart=false
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
environment=PYTHONUNBUFFERED=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:config-restart-listener]
command=/usr/bin/python3 /app/restart_listener.py
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0